; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	Y:\VMWARE_SHARED\CINTERMEDIATE\2010_ASM\call.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_foo
PUBLIC	_main
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2010_asm\call.c
_TEXT	SEGMENT
_main	PROC

; 6    : {

	push	ebp
	mov	ebp, esp

; 7    :     foo();

	call	_foo

; 8    : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2010_asm\call.c
_TEXT	SEGMENT
_foo	PROC

; 3    : void foo() {}

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_foo	ENDP
_TEXT	ENDS
END
