; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	Y:\VMWARE_SHARED\CINTERMEDIATE\2010_ASM\calling_convention1.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_foo
PUBLIC	_main
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2010_asm\calling_convention1.c
_TEXT	SEGMENT
_main	PROC

; 7    : {

	push	ebp
	mov	ebp, esp

; 8    :     foo(1, 2);

	push	2
	push	1
	call	_foo
	add	esp, 8

; 9    : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2010_asm\calling_convention1.c
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_foo	PROC

; 3    : {

	push	ebp
	mov	ebp, esp

; 4    : }

	pop	ebp
	ret	0
_foo	ENDP
_TEXT	ENDS
END
