; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	Y:\VMWARE_SHARED\CINTERMEDIATE\2020_ADVANCED_FUNCTION\variadic_feature2.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f1
PUBLIC	_f2
PUBLIC	_f3
PUBLIC	_main
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2020_advanced_function\variadic_feature2.c
_TEXT	SEGMENT
_main	PROC

; 8    : {

	push	ebp
	mov	ebp, esp

; 9    :     f1(3,1,2,3);

	push	3
	push	2
	push	1
	push	3
	call	_f1
	add	esp, 16					; 00000010H

; 10   :         // 인자를 스택에 넣고
; 11   :         // call _f1
; 12   :         // add esp, 16
; 13   :     f2(3,1,2,3);

	push	3
	push	2
	push	1
	push	3
	call	_f2
	add	esp, 16					; 00000010H

; 14   :     f3(3,1,2,3);

	push	3
	push	2
	push	1
	push	3
	call	_f3
	add	esp, 16					; 00000010H

; 15   : 
; 16   : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2020_advanced_function\variadic_feature2.c
_TEXT	SEGMENT
_n$ = 8							; size = 4
_f3	PROC

; 5    : void __fastcall f3(int n, ...) {}

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_f3	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2020_advanced_function\variadic_feature2.c
_TEXT	SEGMENT
_n$ = 8							; size = 4
_f2	PROC

; 4    : void __stdcall f2(int n, ...) {}        // ret 16

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_f2	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File y:\vmware_shared\cintermediate\2020_advanced_function\variadic_feature2.c
_TEXT	SEGMENT
_n$ = 8							; size = 4
_f1	PROC

; 3    : void f1(int n, ...) {} // __cdecl

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
_f1	ENDP
_TEXT	ENDS
END
